config/routes.rb
Puck::Application.routes.draw do
  root :to => 'home#index'

  match 'home/:action/:id' => 'home'
 
  resources :missions do
    collection do
      get 'mostrecent(/:id)', to: 'missions#mostrecent'
    end
    resources :logs
    resources :responders do
      collection do
        get 'search', to: 'responders#search'
        put ':id/team(/:team_id)', to: 'responders#team'
      end
    end
    resources :roster_timelines do
    end
    resources :teams do
      collection do
        get 'builder', to: 'teams#builder'
      end
    end
  end

  resources :commands

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :check_for_mobile

	def index
		@activeMission = Mission.order(:started).last
	end

	def setSystemTime
		date = params[:id].to_i
		status = 422
		if (date > 631180800)
			`sudo date --set=@#{date}`
			status = 200
		end
		render :nothing => true, :status => status, :content_type => 'text/html'
	end
end

app/views/home/index.html.erb
<!-- ko foreach: recent -->
<div style="box-shadow:rgba(10,10,10,0.5) 3px 3px 5px; border-radius:8px; border:solid 2px #444444; padding:5px; display:inline-block; margin-bottom:10px; width:20em">
<h2 data-bind="text:title" style="margin:0px;" ></h2>
<span data-bind="text:started.toString('yyyy-MM-dd HH:mm')" ></span>
<h4>
<a data-bind="attr: { href: '<%= missions_path %>/' + id}">Details</a>&nbsp;
<a data-bind="attr: { href: '<%= missions_path %>/' + id + '/logs' }">Logs</a>&nbsp;
<a data-bind="attr: { href: '<%= missions_path %>/' + id + '?mobile_once=1#rosterPage' }">Roster</a>&nbsp;
<a data-bind="attr: { href: '<%= missions_path %>/' + id + '/teams/builder' }">Teams</a>
</h4>
</div><br/>
<!-- /ko -->
<div data-bind="text: noMissionText"></div>

<input type="button" value="Start New Mission" data-bind="click: doNewMission" />

<script type="text/javascript">
var PageModel = function()
{
	var self = this;

	this.recent = ko.observableArray();
  this.noMissionText = ko.observable("Loading ...");

	this.doNewMission = function()
	{
		window.location.href = '<%= new_mission_url %>';
	}

  this.loadRecent = function()
  {
    $.ajax({type:'GET', url: '<%= root_url %>missions/mostrecent/5'})
     .done(function(result) {
       $.each(result, function(i,val) { convertToDate(val, ['started']) });
       self.recent(result);
       self.noMissionText((result.length > 0) ? "" : "No recent missions");
     });
  }
}


$(document).ready(function() {
  var model = new PageModel();
  ko.applyBindings(model);
  model.loadRecent();
});

</script>