config/routes.rb
Puck::Application.routes.draw do
  root :to => 'home#index'

  match 'home/:action/:id' => 'home'
 
  resources :missions do
    collection do
      get 'mostrecent(/:id)', to: 'missions#mostrecent'
    end
    resources :logs
    resources :responders do
      collection do
        get 'search', to: 'responders#search'
        put ':id/team(/:team_id)', to: 'responders#team'
      end
    end
    resources :roster_timelines do
    end
    resources :teams do
      collection do
        get 'builder', to: 'teams#builder'
      end
    end
  end

  resources :commands

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  include ActiveUUID::UUID

  has_many :logs
  has_many :units
  has_many :responders
  has_many :teams

  attr_accessible :county, :number, :started, :title, :briefing

	validates :title, :presence => true
	validates :started, :presence => true

  def create_children(keys)
    keys ||= {}
    base = Team.new({ :name => '_base', :kind => :base,
                      :id => keys['base_id'], :mission_id => self.id},
                    :without_protection => true)
    val = base.save
    keys['base_id'] = base.id.as_json

    staging = Team.new({ :name => '_staging', :kind => :staging,
                         :id => keys['staging_id'], :mission_id => self.id},
                       :without_protection => true)
    val &= staging.save
    keys['staging_id'] = staging.id.as_json

    val
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_filter :check_for_mobile

  def show
    @mission = Mission.find(UUIDTools::UUID.parse(params[:id]))
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mission }
    end
  end

  # Get the N (default 1) most recent missions
  # GET /missions/mostrecent
  # GET /missions/mostrecent/5
  def mostrecent
    count = params[:id] || 1
    render :json => Mission.find(:all, :limit => count, :order => 'started DESC')
                    .to_json(:only => [:id, :title, :number, :started])
  end

  def new

  end

  def create
    cmd = Commands::UpdateCommand.make(nil, 'Mission', params[:mission])
   
    respond_to do |format|
      if cmd.execute
        broadcast "missions/new", cmd.model.to_json

        format.html # new.html.erb
        format.json { render :json => cmd.model }
      else
        format.html { render :action => "new" }
        format.json { render :json => cmd.model.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    cmd = Commands::UpdateCommand.make(params[:id], 'Mission', params[:mission])

    respond_to do |format|
      if cmd.execute
        broadcast "missions/update", cmd.model.id.to_json

        format.html
        format.json { render :json => cmd.model }
      else
        format.html { render :action => "edit" }
        format.json { render :json => cmd.model.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    cmd = Commands::DestroyCommand.make(params[:id], 'Mission')
    if (cmd.execute) then
	    broadcast "missions/delete", "\"#{params[:id]}\""
	    render :json => params[:id]
    end
  end

end

app/views/missions/new.html.erb
<h2>Start new mission</h2>
<!--
          <textarea id="newMsg" data-bind="value: nextLogEntry, hasfocus: focusForm, event: { keyup
: cancelScroll }, css: { errInput: nextLogErrors().message }, ctrlEnter: doSave" style="width:40em;
 height:4em;"></textarea><br/>
message"></div>
-->

<table>
<tr><td><label for="createTitle">Title</label></td>
  <td><input id="createTitle" type="text" data-bind="value:mission.title, css: { errInput: errors().title }"/>
<span data-bind="visible: errors().title, text: errors().title" class="fieldErr"></span></td></tr>

<tr><td><label for="txtWhen">Started</label></td>
<td><input id="txtWhen" type="text" data-bind="value:mission.started.formatted, css: {errInput: errors().started }"/>
<span data-bind="visible: errors().started, text: errors().started" class="fieldErr"></span></td></tr>

<tr><td><label for="createNumber">DEM#</label></td>
<td><input id="createNumber" type="text" data-bind="value:mission.number, css:{errInput:errors().number}"/>
<span data-bind="visible: errors().number, txt: errors().number" class="fieldErr"></span></td></tr>
</table>
<button data-bind="click:doSave">Start</button>

<script type="text/javascript">
var PageModel = function()
{
  var self = this;
  this.mission = new MissionModel({});
  this.mission.started(new XDate().setMinutes(Math.round((new XDate().getMinutes() - 15) / 30) * 30))
  this.errors = ko.observable({});

  this.doSave = function()
  {
    self.errors({})
    $.ajax({ type: 'POST', url: siteRoot + 'missions.json', data: '{"mission": '+ko.toJSON(self.mission)+'}', dataType: 'JSON', contentType:'application/json; charset=utf-8'})
    .done(function(result) {
      window.location.href = siteRoot;
    })
    .fail(function(jhr) {
      if (jhr.status == 422) {
        self.errors($.parseJSON(jhr.responseText));
      }
      else { alert('General Error: ' + jhr.responseText); }
    })
    ;
  }
}

var model;
$(document).ready(function() {
  model = new PageModel();
  ko.applyBindings(model);
});

</script>

app/views/missions/show.html.erb
<h2 style="margin-top:1.2em;"><span data-bind="text: mission.title"></span></h2>

<h4>Mission Briefing</h4>
<div data-bind="ifnot:isEditingBrief">
<pre data-bind="text: mission.briefing">
</pre>
<input type="button" value="Edit Briefing" data-bind="click: editBrief" />
</div>
<div data-bind="if:isEditingBrief">
<textarea data-bind="value: newBriefText" rows="10" cols="60"></textarea>
<br/>
<input type="button" value="Save Briefing" data-bind="click: saveBrief" />
<input type="button" value="Cancel" data-bind="click: cancelBrief" />
</div>
<script>
var model;

var PageModel = function(apiMission)
{
  var self = this;
  this.mission = new MissionModel(apiMission);

  this.newBriefText = ko.observable();
  this.isEditingBrief = ko.observable(false);

  this.editBrief = function() {
    var text = self.mission.briefing();
    if (!text || text == "") text = briefTemplate
       .replace("[Mission Name]", self.mission.title())
       .replace("[Current Time]", new XDate().toString("yyyy-MM-dd HH:mm"));
    self.newBriefText(text);
    self.isEditingBrief(true);
  };
  
  this.saveBrief = function() {
    $.ajax({ type: 'PUT', url: '<%= mission_path(@mission) %>.json', data: '{"mission":' +ko.toJSON({briefing: self.newBriefText})+'}', dataType: 'JSON', contentType:'application/json; charset=utf-8'})
      .done(function(result) {
        self.mission.briefing(result.briefing);
        self.isEditingBrief(false);
      })
      .fail(function(jhr) {
        if (jhr.status == 422) {
        }
        else { alert('General Error: ' + jhr.responseText); }
      })
      ;


  };
  this.cancelBrief = function() {
    self.isEditingBrief(false);
  };
}

$(document).ready(function() {
  model = new PageModel($.parseJSON('<%= j(@mission.to_json.html_safe) %>'));

  ko.applyBindings(model);

  var faye = new Faye.Client('<%= faye_url %>/faye');
});
var briefTemplate = "[Mission Name]\nUpdated [Current Time]\n\nOverview:\n[summary]\n\nI/C: [enter name]\nOperations: [enter name]\nPlanning: [enter name]\n\nPrimary Frequency: [frequency details]\nMap Datum: [UTM NAD27, ddd mm.mmmm WGS84, etc]\n\nWeather Forecast:\n[report]\n\nSubject Description:\n[report]\n";
</script>